### ISSUE TITLE
Sanitize chat inputs

### ISSUE THREAD

**Issue by Liquid-Blocks** [Spacetime-Meta/spacetime-standard-kit#138]
When a new message is sent to the chat box, there is no filtering of the message to remove HTML tags or any other potentially harmful content.

**The priority is to remove the `<script>` tag since injection is a security issue.**

If possible (with no compromises on security), allow only the HTML tags related to text formatting ex: `<b>`, `<u>` , `<i>`

**Comment by codeeMadness** [comment]
Hi @Liquid-Blocks ,

- for this issue, I will make use of peerjs-group (has implemented in #148 ). This library provides a function to support this.
- about other tags such as `<b>`, `<u>` , `<i>` I think we should plan to allow box chat support RichTextHTML in future. This will help to prevent security injections.
