### ISSUE TITLE
Prevent double connection

### ISSUE THREAD

**Issue by Liquid-Blocks** [Spacetime-Meta/spacetime-standard-kit#139]
In the `RemoteController`, there should be a verification to prevent users from being connected twice.

1. It should not be possible to call `RemoteController.connectToPeer(peerId)` on a peer we are already connected to.
2. There should be a verification before calling `RemoteController.connections.push(newConnection)`, to prevent doubles in the array.

![Image](https://user-images.githubusercontent.com/46661277/171195559-e6f142af-1d04-4c46-84bf-ee1b77b5d050.png)

![Image](https://user-images.githubusercontent.com/46661277/171195732-555edb20-b32d-4bb6-a97f-b8f0173c4af9.png)

**Comment by codeeMadness** [comment]
Hi @Liquid-Blocks,
This issue is already resolved. correct?
I have tested on the newest version. It seems fine.
If ok, I will close this issue. or else, just help to tell me if we have any other issues relate to this.

**Comment by Liquid-Blocks** [comment]
Yes this issue seems to have been solved during the latest updates
