### ISSUE TITLE
Find a way to compress model size

### ISSUE THREAD

**Issue by codeeMadness** [Spacetime-Meta/spacetime-standard-kit#156]
Working with Blender designer to make model light-weight

**Comment by codeeMadness** [comment]
Check Blender designer work at: https://drive.google.com/drive/folders/1vyTlq63aZqIrBqDvW25lZNs8apRjcV7f?usp=sharing

**Comment by codeeMadness** [comment]
@jason065 has provided 3D models from customer, request to deploy on cdn: https://drive.google.com/file/d/1Hxy0ji9T-is-hJ1CwYhQpFsB53S3L0mj/view

**Comment by Liquid-Blocks** [comment]
This problem was solved
