### ISSUE TITLE
Update groups

### ISSUE THREAD

**Issue by Liquid-Blocks** [Spacetime-Meta/spacetime-standard-kit#162]
Update the Ui to the new system

should include the management of chat messages for the group feature. Right now all the chat messages are the same color. I think it would be good to have the direct message and the group message appear differently, so that the user knows where the message originate from.

**Comment by codeeMadness** [comment]
Hi @Liquid-Blocks, for this task, should we change the menu from horizontal into vertical. I'm going to create a new panel like Group Management. It might be not good in UI if too many menu tabs on top.

**Comment by Liquid-Blocks** [comment]
Hi @codeeMadness, you are right that having to many tabs is not good for user experience. 

But I am not sure about going vertical. It would solve our problem for now but, as we keep adding more tabs we risk having the same problem on the vertical menu.

What do you think about a 'burger' menu ? 
![image](https://user-images.githubusercontent.com/46661277/174607621-6de283e9-05c5-45e3-a59d-f9a818990a2c.png)
<br><br><br>
On click, the menu would expand like this
![image](https://user-images.githubusercontent.com/46661277/174608236-5b6b0ad2-5360-432a-bd1e-e6aff720486f.png)

**Comment by codeeMadness** [comment]
Hi @Liquid-Blocks,

Yup. Let's implement this way.

**Comment by Liquid-Blocks** [comment]
This will be reopen as a complete feature. will link.
