### ISSUE TITLE
Need help to reduce path reference

### ISSUE THREAD

**Issue by codeeMadness** [Spacetime-Meta/spacetime-standard-kit#165]
Hi Liquid, 
As you know, **ConnectionOptions.js** met a problem too-long path when we do some actions relates to Github.
We can totally deal with this when using some commands provided by Github.
However, when I tried to deploy on internal server (I mean I have to place our core in server, not connected with any source control), it met the same issue.
Should we change a little bit for this, to make the path shorter (such as move files to upper level folder)? Or could make the config inside the core to handle this issue?

Many thanks.

**Comment by codeeMadness** [comment]
Feel free to ignore if you feel no need

**Comment by Liquid-Blocks** [comment]
Hi @codeeMadness if it causes you a problem for the deployment I will reorganize the hierarchy to shorten the path.

**Comment by codeeMadness** [comment]
Hi @Liquid-Blocks,
Many thanks

**Comment by codeeMadness** [comment]
Is there any way we can manage code structure using MVC model or other models? and we can control our files using name convention?

**Comment by Liquid-Blocks** [comment]
For the UI we can go toward something that is more MVC like, but I don't think we can fit the whole system into the MVC model since the VirtualEnvironment is somewhere between a controller and a view and we don't have specific entry point for the data.

**Comment by codeeMadness** [comment]
To be honest,
For the UI, it's quite good.
However for the code, it's quite heavy in structure, requires much nested class.

**Comment by Liquid-Blocks** [comment]
Hi @codeeMadness , the path was shorten in the PR #167. Does that solve your problem?

**Comment by codeeMadness** [comment]
many thanks. let me take a look on it.
