### ISSUE TITLE
Optimize avatar rotation

### ISSUE THREAD

**Issue by Liquid-Blocks** [Spacetime-Meta/spacetime-standard-kit#59]
**This issue is a following of the issue [#49 Character face walking direction](https://github.com/Spacetime-Meta/spacetime-standard-kit/issues/49)**

[The closing message on issues 49:](https://github.com/Spacetime-Meta/spacetime-standard-kit/issues/49#issuecomment-1125493929)
---
As shown in the image below, the input catching logic is duplicated between the `PlayerLocal.update` and `AvatarController.rotateFaceDirection`.  

![image](https://user-images.githubusercontent.com/46661277/168177105-305f314c-7372-4eba-9cfa-772d6e6dfaf2.png)

Ideally, to optimize the update loop, we would:
1. Catch the user input only in the `PlayerLocal`.
2. Execute the logic to find the new rotation inside `PlayerLocal.update` 
3. Adjust the capsules rotation using the attribute `THREE.Object3D.quaternion` from its parent. 
4. Pass the quaternion to the `AvatarController` as an argument of `AvatarController.update`
5. Then the `AvatarController` would only copy the capsules facing rotations using `AvatarController.applyQuaternion`, inherited from its `THREE.Object3D` parent.
---

**Comment by codeeMadness** [comment]
Hi @Liquid-Blocks,

I still don't know how to use _"applyQuaternion"_ as your suggestion. Did try, but the model still not rotate.
Please help to take a look on my branch, and give any further advise. It would be much appreciate.

**Comment by Liquid-Blocks** [comment]
@codeeMadness No problem, I will open the branch and take a look, thank you

**Comment by Liquid-Blocks** [comment]
Hi @codeeMadness , I have solved the payer rotation in a new branch that I merged into develop in PR #70,

The final solution uses the horizontal velocity to find the facing rotation.
