### ISSUE TITLE
Implement running jump animation

### ISSUE THREAD

**Issue by Liquid-Blocks** [Spacetime-Meta/spacetime-standard-kit#62]
The actual only jump animation of the array is ok for *idle->jump* but looks very weird when doing *walk->jump* and *run->jump*

https://user-images.githubusercontent.com/46661277/168200739-d3b0e293-9d38-4045-8b02-193c13b7e861.mp4

The goal of this issue is to find a new animation that works on the vanguard and can fit with the *walk->jump* and *run->jump* transitions

**Comment by codeeMadness** [comment]
Hi @Liquid-Blocks ,

Should I look for new animation on mixamo? or any where else that I could take a look?

**Comment by Liquid-Blocks** [comment]
Hi @codeeMadness, the only place I know for animations is mixamo, but anything is good.
