### ISSUE TITLE
Way to remove friends from list

### ISSUE THREAD

**Issue by Liquid-Blocks** [Spacetime-Meta/spacetime-standard-kit#90]
As of now there is only a way to add new friends in the list, there should be a way to remove them and disconnect.
![Image](https://user-images.githubusercontent.com/46661277/169178809-5ead6429-0fc7-4558-903b-39d1fd4cffaf.png)

Assignee is free to chose how the interface is organized, don't waste to much time on the visual as we will redo everything according to UI design.

The `friendList` is stored in `localProxy.friendList` for persistence.  

I strongly recommend commenting the following section while development:
![image](https://user-images.githubusercontent.com/46661277/169179345-aa02769b-05cc-4908-be8a-86aa22b8fbda.png)

**Comment by codeeMadness** [comment]
Hi @Liquid-Blocks ,
for this enhancement, one issue still not resolve yet.
when disconnect a peer, it does not update friend list on that peer.
however, my PR has covered enough requirements for this task.
